### ISSUE TITLE
启动无权限，各种方法都试过，启动就退出，求指导！

### ISSUE THREAD

**Issue by ouxiand** [jiyeyuran/mediasoup-go-demo#6]
感谢分享这么优秀的项目，编译启动出错，详细内容如下：
[90m2022-11-07T22:42:32+08:00[0m [33mDBG[0m [1mWorker[0m[36m >[0m constructor() [36msettings=[0m{"CustomOptions":null,"WorkerBin":"/go/mediasoup-go-demo/server","WorkerVersion":"","appData":{},"logLevel":"warn","logTags":["info","ice","dtls","rtp","srtp","rtcp","rtx","bwe","score","simulcast","svc","sctp"],"rtcMaxPort":7100,"rtcMinPort":7003} [36mv=[0m1
[90m2022-11-07T22:42:32+08:00[0m [33mDBG[0m [1mWorker[0m[36m >[0m spawning worker process [36margs=[0m"--logLevel=warn --logTags=info --logTags=ice --logTags=dtls --logTags=rtp --logTags=srtp --logTags=rtcp --logTags=rtx --logTags=bwe --logTags=score --logTags=simulcast --logTags=svc --logTags=sctp --rtcMinPort=7003 --rtcMaxPort=7100" [36mbin=[0m/go/mediasoup-go-demo/server [36mv=[0m1
panic: fork/exec /go/mediasoup-go-demo/server: permission denied

goroutine 1 [running]:
main.NewServer({{0x96f432, 0x9}, {{0x96e0d6, 0x7}, 0x1b59, {{0xc0002b0180, 0x30}, {0xc0002b01b0, 0x2e}}}, {0x4, ...}})
	/go/mediasoup-go-demo/server/server.go:60 +0x528
main.main()
	/go/mediasoup-go-demo/server/main.go:41 +0x3ff

请问如何处理？

**Comment by ouxiand** [comment]
路径问题

**Comment by huangqingbiao8831** [comment]
如何解决的，我的路径没有问题，也出现这种问题。

**Comment by huangqingbiao8831** [comment]
好像搞定了，目录后面要把应用程序名字也带上。

**Comment by huangqingbiao8831** [comment]
大神这个项目不错，花点时间把mediasoup那个js给换掉是不错的想法。
